### ISSUE TITLE
Unable to use search string while creating env

### ISSUE THREAD

**Issue by asharma3-ias** [Security-Phoenix-demo/autoconfig#35]
Use case:
We want to create an environment and add a service based on the rule below:
If any asset contains the {string} as part of the name, it should be added as a service. 
I have tried this:

```
Environment Groups:
- Name: Production
  Type: CLOUD
  Status: Production
  Responsable: a@b.com
  Tier: 8 #importance from 1-10
  Status: Production
  TeamName: {Team}
  Services:
  - Service: {service}
    Type: Cloud
    SearchName: {string}
```

and it fails with:
YamlHelper.py", line 98, in populate_environments_from_env_groups\n    'Association': service['Association'],\n                   ~~~~~~~^^^^^^^^^^^^^^^\nKeyError: 'Association'\n
